### ISSUE TITLE
Add storage path as a config option

### ISSUE THREAD

**Issue by MindFreeze** [hassio-addons/addon-influxdb#13]
# Problem/Motivation

Currently I can't find a way to store influxdb data on an external drive, except forking the addon.

## Proposed changes

It would be great if I could specify a directory for the data. Then I could mount an external drive somewhere in `share` and use that for InfluxDB. This method is proposed here https://www.home-assistant.io/hassio/external_storage/
 Something like this:
```
    "log_level": "info",
    ...
    data_path: "/share/influxdb"
```
Another option is to just use `share` instead of `/data` with a fixed directory name, but I think a config option is more flexible.

<blockquote><img src="https://www.home-assistant.io/images/default-social.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/hassio/external_storage/">External device</a></strong></div><div>How to map external device on Hass.io.</div></blockquote>

**Comment by frenck** [comment]
The link you send is not mounting a USB stick in that location, so that is not an option / would not help.
Hass.io exposes a data folder to each add-on, which is, of course, used. I think it would make much more sense if Hass.io actually supported the storage of add-on data on other locations instead of making this kind of "hacky" solutions.

Hence, I'm closing this issue.
